### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by WetABQ** [XiangpengHao/parquet-viewer#14]
<img width="1156" alt="Image" src="https://github.com/user-attachments/assets/91585e3f-c9aa-4ba9-bb4c-a00a63d53405" />

**Comment by Colerar** [comment]
It seems to have been fixed by upstream PR:

https://github.com/seanmonstar/reqwest/pull/2632

However, reqwest has not yet released this bug fix.

Temporary workaround:

```toml
[patch.crates-io]
reqwest = { git = 'https://github.com/seanmonstar/reqwest.git' }
```
